### ISSUE TITLE
IllegalArgumentException during js file generation

### ISSUE THREAD

**Issue by Tapsi** [st-js/st-js#103]
**Error:**

[ERROR] C:\Users\xxx\Documents\CustomWarsTactics\cwtactics\gameSrc\org\wolftec\cwt\sheets\MoveType.java [1:1]: java.lang.IllegalArgumentException: Illegal character in path at index 3: org\wolftec\cwt\sheets\MoveType.js
java.lang.IllegalArgumentException: Illegal character in path at index 3: org\wolftec\cwt\sheets\MoveType.js
	at java.net.URI.create(URI.java:852)
	at java.net.URI.resolve(URI.java:1036)
	at org.stjs.generator.Generator.getRuntimeUri(Generator.java:189)
	at org.stjs.generator.Generator.generateJavascript(Generator.java:176)
	... 

**Description:** I get this error for every source file in my project. So no js files will be generated in the target directory.

**Affected Versions:** 3.2.0

**Environment:** Windows 10

**My Assumption:** The problem is may introduced due the commit ```https://github.com/st-js/st-js/commit/418df4777348abd0506174121508f70224a1e24f```. The ```\``` character in path of the source files produces the error because this character is may not escaped (which is required for an URI as mentioned in the RFC 2396).

**Comment by npiguet** [comment]
Can you double check that the last commit fixes your issue? I couldn't find a way to write a proper automated test for that.

**Comment by Tapsi** [comment]
Reviewed the commit. That should work.

**Comment by npiguet** [comment]
I guess we'll call it fixed then. Don't hesitate to re-open this if you encounter more problems.

**Comment by npiguet** [comment]
FYI: I've release version 3.2.1, it should land in the maven central repositories in the next few minutes.

**Comment by Tapsi** [comment]
Nice job! I'll test the bugfix on the mentioned environment today.

**Comment by Tapsi** [comment]
Fixed.
