### ISSUE TITLE
Add STJS test runner property to pass command line parameters to browser 

### ISSUE THREAD

**Issue by SurgeonY** [st-js/st-js#106]
Sometimes there is need to start browser by STJS test driver runner with specific parameters, e.g. when running on CI to make Chrome writing log files.

Add property similar to **firefox.bin** etc. set of props, something like
**firefox.args, chrome.args, phantomjs.args**.

**Comment by acraciun** [comment]
you can point to a script that launches the browser with your arguments

**Comment by SurgeonY** [comment]
Actually this is the very workaround we used so far.
It's not convenient and that's why this feature request has been created.
Thanks!
