### ISSUE TITLE
FormData bridge is not available

### ISSUE THREAD

**Issue by bogdartysh** [st-js/st-js#113]
Hi,
I see that there is no implementation for FormData of XMLHttpRequest Level 2  (https://developer.mozilla.org/en/docs/Web/API/FormData) in st-js and (?) it's bridge sub-projects.

Is there a planned / project for that?

**Comment by zhuker** [comment]
i have FormData bridge in my fork 
https://github.com/zhuker/html-bridge

**Comment by pascalheraud** [comment]
You should create a pull request in order to merge it into trunk.

**Comment by zhuker** [comment]
@pascalheraud 
https://github.com/st-js/html-bridge/pull/11

**Comment by pascalheraud** [comment]
Thank you !

**Comment by acraciun** [comment]
just merged
