### ISSUE TITLE
Conflicting google guava dependencies

### ISSUE THREAD

**Issue by ecriss** [st-js/st-js#115]
See under "Compile Dependencies"
http://mvnrepository.com/artifact/org.st-js/generator/3.2.2

Version v20141215 of closure-compile upgrades guava dependency from version 17.0 to version 18.0.

This version of the Files.copy method was taken of guava version 18:

https://github.com/st-js/st-js/blob/313cf960c686d3051e5a211571b1d03a2c7beeb0/generator/src/main/java/org/stjs/generator/Generator.java#L251

**Comment by npiguet** [comment]
I'm not sure what's the problem that you are reporting? Does that mean that if we decide to upgrade the dependency to closure-compiler to version r2388, then we'll have an issue with guava 18.0?

Is this actually a problem with the current released version of st-js?

What is the problem that we need to fix?

**Comment by ecriss** [comment]
The problem is because guava upgrades to version 18, and the version of the Files.copy method being used on that link I included uses a deprecated and removed version of Files.copy. So the build ends up complaining that the method doesn"t exist. As a fix that code I linked to should be changed to be compatible with guava 18 since that ends up being the requirement anyway. Yes, I'm experiencing this issue in the latest release: 3.2.2

**Comment by npiguet** [comment]
What do you mean by "guava upgrades to version 18"? In the stjs maven 
plugin build the version of guava is fixed to 17, it can't just upgrade 
itself to 18.

Are you using another plugin in your maven build that has a dependency on 
guava 18?

**Comment by ecriss** [comment]
I'm trying add support for the latest version of stjs for the gradle plugin here:

https://github.com/dzwicker/st-js-gradle-plugin

Perhaps there's something I'm missing. I'll investigate further and comeback to report on what I find.

**Comment by ecriss** [comment]
closure-compiler version v20141215  lists guava version 18.0 as a dependency which is causing version 17 to be evicted. But I'm able to get around this issue by forcing gradle to use guava version 17 using:

compile('com.google.guava:guava:17.0') { force = true }

So far I'm able to compile successfully.

**Comment by npiguet** [comment]
I believe that this was fixed by pull request #118
