### ISSUE TITLE
org.stjs.command.line.CommandLine and org.stjs.command.line.ProjectCommandLine do not have options for installing stjs.js

### ISSUE THREAD

**Issue by philip-wernersbach** [st-js/st-js#117]
See title. We have a large project that uses Ant, so we cannot use the st-js Maven plugin. We've pieced together a solution that involves Ant calling `org.stjs.command.line.ProjectCommandLine`, which works but does not have an option for installing the `stjs.js` file, making it useless.

**Comment by npiguet** [comment]
We plan on making stjs.js an indépendant artifact (basically it's own 
webjar). Would this solve your problem?

**Comment by philip-wernersbach** [comment]
Yes, that would solve our problem.

**Comment by onigoetz** [comment]
Close as this will be solved in #116
