### ISSUE TITLE
Need anything contributed?

### ISSUE THREAD

**Issue by zhuker** [st-js/st-js#130]
Hey guys
Just wanted to thank you for this great project!
It helps us a lot in our day to day dev.
Are there any issues/missing features you would want to have added - let me know
Are you accepting donations?

**Comment by acraciun** [comment]
thank you for your offer!
of course any help in continuing the project would be greatly appreciated - as you saw we've been less active lately. Does your offer still stands?

Regarding the donations - thanks - but we didn't have this in mind when we created the project :)

**Comment by zhuker** [comment]
the offer does still stand, i would like to see the project evolve

**Comment by acraciun** [comment]
great!!
so unless you have already in mind as said, some help with the current list of issues would be greatly appreciated. for example #125

**Comment by acraciun** [comment]
we can continue the discussion by email ax.craciun@gmail.com
