### ISSUE TITLE
example testing asynchronous code with test-helper

### ISSUE THREAD

**Issue by zhuker** [st-js/st-js#132]
my tests are expecting an event which happens within a second of starting the test
but test runner stops before such event happens

any ideas?

**Comment by acraciun** [comment]
unfortunately in Javascript there is no way to wait - as there is a single thread.
what we did was to forbid the direct usage of setTimeout and setInterval, but instead make a small library that in prod code does the same think, but in test it only puts the callbacks in a list.
This way, anywhere in your test (probably just before making your checks), you can ask this small library to execute whatever timers are created.
