### ISSUE TITLE
Referencing constants

### ISSUE THREAD

**Issue by pascalheraud** [st-js/st-js#137]
Hello,
We often want to use constants (final static public String ) coming from pure Java classes like Spring controllers, for example to make some URLs used from JS code.

Example, 
The controller class:

``` java
public interface IHMConstants {
   public final static String URL1 = "/myurl/";
}

``` java
@Controller
public class MyController {
   @RequestMapping(IHMConstants.URL1)
    public String myMethod1() {
         ...
   }

}
```

The STJS class : 

``` java
public class MyScreenJS {

       public void onClickButton() {
             jQuery.ajax(new AjaxParams() {{
                     url = IHMConstants.URL1;
             }});
       }
}
```

Can we do that in STJS ( I tried several ways but didnt manage it) ?
If we have some proposals, I can implement it.

We could simply import any constant found in external class but it could be different from actual behaviour.
I thought we can have a kind of "STJSConst" annotation that will copy any const referenced : 

``` java
public class MyScreenJS {

       @STJSConst public final static String URL1 = IHMConstants.URL1;

       public void onClickButton() {
             jQuery.ajax(new AjaxParams() {{
                     url = URL1;
             }});
       }
}
```

Not sure it could be the best way but it would do the job.
Any thoughts ?

**Comment by acraciun** [comment]
I presume public class MyController is a server-side class right?
What we did - to make sure we don't mix the different classes - was to create 3 artifacts - client, shared and server. In shared you'd put the code that you need to share - typically your constants.

We also have the annotation: https://github.com/st-js/st-js/blob/master/shared/src/main/java/org/stjs/javascript/annotation/ServerSide.java
that indicates the transpiler to ignore that code (as it's useful only on the server).

Keeping both your client and server in the same artifacts may be dangerous as you may mistakenly call code intended to be transpiled from your server code - and the results - well they may be unexpected

**Comment by pascalheraud** [comment]
Good to know that the ServerSide annotation exists, thank you.

My purpose was to use constants from the client side, but without create in client class to hold constants. It could be great to have the mean to copy the constant in the client side.
I will modify the issue to explain it better.
