### ISSUE TITLE
for...in transpiles wrongly

### ISSUE THREAD

**Issue by AndreySushkovich** [st-js/st-js#139]
The way STJS transpiler converts for-each to for-in is incorrect (version **3.3.2**).

Test Case:

    for (String i : createdEntries) {
        Entry entry = createdEntries.$get(i);
        this.subscriptions.notifyCreated(entry);
    }

is transpiled to

    for (var i in createdEntries) {
        if (!(createdEntries).hasOwnProperty(i))
            continue;
        var entry = createdEntries[i];
        this.subscriptions.notifyCreated(entry);
    }

Note that ')' in `if (!(createdEntries).hasOwnProperty(i))` is misplaced which results in an array being converted to boolean (so the whole check is pointless).

**Possible outcome:**
Adding a method to an iterable object may (and probably will) cause undefined behavior.

**Comment by acraciun** [comment]
I don't understand the problem.
For example if you have 
var a = [1,2];
(a) is also an array

**Comment by AndreySushkovich** [comment]
Hi @acraciun,
I was sure it was (!createdEntries) and not !(createdEntries) :) So yes, not a bug.
Thanks for your time and reply anyway.
