### ISSUE TITLE
Annotation to bridge using a different name

### ISSUE THREAD

**Issue by pascalheraud** [st-js/st-js#17]
When writing a bridge, it could be nice to have an annotation to have a different name between the bridge class and the JS class.

**Comment by npiguet** [comment]
Can you give an example of a case where this would be needed?

**Comment by pascalheraud** [comment]
Sometimes, js library have bad names and we want to change it.
Some important classes have a so common name that we want to change it, for example we did a bridge for Google Maps, the main class is "Map", we'd like it to be 'GoogleMap". I know we have namespaces in Java but it's so much easier to not have a 5563th class named 'Map'...

**Comment by npiguet** [comment]
This seems like a valid use case.

Also, consider donating your google maps by making a Github project for it and telling us about it so we can add it to the list of bridges.

**Comment by pascalheraud** [comment]
We made several wrappers for the following js libraries that we could share : 
- blockUI
- cloudinary
- pickaday
- fancybox
- highcharts
- jqgrid
- alertify
- momentjs
- googlemaps

Do you want me to add all these wrappers to a new GitHib project as well ?

**Comment by npiguet** [comment]
It would be nice if you could do one github project for each Bridge that is more or less complete. We can then add them to the "Bridges" page on the website, and/or fork them in the st-js team.

**Comment by onigoetz** [comment]
@pascalheraud any news on your bridges ? we would really like to be able to propose more bridges

**Comment by pascalheraud** [comment]
Hello
Sorry but I missed notifications...

I made 3 repos for sharing bridges : 
- https://github.com/LaRoueVerte/st-js-parsley
- https://github.com/LaRoueVerte/st-js-cloudinary
- https://github.com/LaRoueVerte/st-js-googlemap

Tell me if it is what you were expecting me to provide.

Cheers.

**Comment by onigoetz** [comment]
Thank you that's very nice.

Did you release them somewhere, or they're only snapshots for the moment ?

**Comment by pascalheraud** [comment]
You mean release as a maven artefact ?
I never pushed a project to maven's central. I can do it if you think this is the best way.

Do you think :
- We should manage the bridges ourselves and you can reference them ?
or 
- You take ownership of the code and we will make pull requests after ?

Pascal.

**Comment by onigoetz** [comment]
I don't know what you prefer.

In both cases we can reference it on our website to say that the bridge is available.

However if we take the ownership of the code, we would need to change the package name to deploy on maven central. Also, as we don't directly use these bridges, we would not maintain them actively.

If you keep the ownership on your side and deploy on maven central (which I heard from @npiguet and @acraciun is quite easy, except the first time) you could evolve your bridge at your rythm.

**Comment by pascalheraud** [comment]
Ok, 
I think we will deploy them on maven central and let you know when it will be available.
Do we keep the name of the artifacts or keep them named in stjs way ?

Pascal.

**Comment by onigoetz** [comment]
You can keep the `artifactId` but you will need to change the `groupId` as on maven central you can only deploy on group id's for which you own the domain.

For the version we have naming scheme to ease the understanding : 

For example the Bridge for jquery 1.11.3 would be : `1.11.3bv1` so basically `<library_version>bv<1-9>`

So you directly know for which version of a library your bridge is, and you can update the bridge version with `bv`.

**Comment by pascalheraud** [comment]
Ok, my first artifact pushed to maven's central :)
https://github.com/LaRoueVerte/st-js-cloudinary
Maven : 
<dependency>
    <groupId>net.laroueverte.stjs.bridge</groupId>
    <artifactId>cloudinaryjs</artifactId>
    <version>1.0.24bv1</version>
</dependency> 

I will share more bridges if you reference them from st-js website.

**Comment by pascalheraud** [comment]
up

**Comment by pascalheraud** [comment]
Hello, @onigoetz  
Any news for that work ?

Cheers,
Pascal.

**Comment by acraciun** [comment]
Your bridge was added here: http://st-js.github.io/bridges.html
Thank you.
Please open another issue if you have additional bridges to share!

**Comment by pascalheraud** [comment]
Thank you, I'll share other bridges as soon I'll get enough time.
