### ISSUE TITLE
Make ST-JS play well with webjars

### ISSUE THREAD

**Issue by npiguet** [st-js/st-js#58]
There is already a great way of packaging JavaScript source code with maven: The webjars repository: http://www.webjars.org/

ST-JS is currently ignoring this existing infrastructure in different ways:
 - by default stjs-maven-plugin doesn't build Servlet 3 compatible jars (it doesn't make use of the special properties of META-INF/resources). This means that users need to do all sorts of strange manipulations in their webapp jars to server ST-JS javascript files.
 - ST-JS bridges package their own version of the javascript libraries they bridge. They could instead declare the correct webjars dependency, making it easier for webapplications that already use webjars to figure out the correct version of Javascript dependencies
 - ST-JS TestDriverRunner doesn't specifically support webjars or META-INF/resources, forcing users to explicitly manually define scripts that they depend on.

ST-JS should try to improve on this situation.

**Comment by onigoetz** [comment]
Looks very interesting.
Would be nice if the bridges had a dependency on the corresponding webjar

**Comment by npiguet** [comment]
Closed by various recent commits to master
