### ISSUE TITLE
Generate private methods without attaching them to the prototype or constructor

### ISSUE THREAD

**Issue by onigoetz** [st-js/st-js#67]
I see that private methods are generated by binding them to the constructor or to the object's prototype.

As we know the method is private and it can't be used elsewhere (java compilation would fail) Why not generate private methods inside the class privately.

This would bring the following improvements:
- plays well with minification
- will not be called from pure JS code

We can even imagine extending this to properties.

**Comment by onigoetz** [comment]
Forgot to precise, if you're interested in this, I can try to make a Pull Request with this feature

**Comment by acraciun** [comment]
in fact you have to take into consideration "protected" and the fact that the private methods must also access "this" properties and call other public methods. Can you post already here how do you see it working?

**Comment by onigoetz** [comment]
Yeah I thought about protected, and I think it should be treated as public.

It would need some tests, but I see them working like this : 
Original source:
```javascript
ContextMenu = function(items, withDelete) {
    ... constructor ...
};
stjs.extend(ContextMenu, AbstractPopupContainer, [], function(constructor, prototype) {
    prototype.buildMenu = function(items) {
        ...
        var menuItems = this.buildMenuItems(items);
        ...
    };
    prototype.buildMenuItems = function(models) {
        ... private logic here ...
    };
}, {...}, {});
```

New source:
```javascript
ContextMenu = function(items, withDelete) {
    ... constructor ...
};
stjs.extend(ContextMenu, AbstractPopupContainer, [], function(constructor, prototype) {
    prototype.buildMenu = function(items) {
        ...
        var menuItems = buildMenuItems(items);
        ...
    };
    function buildMenuItems(models) {
        ... private logic here ...
    };
}, {...}, {});
```

you will probably ask me "what if a private is called form the constructor?"
to that I answer that we could be able to solve it like this:
```javascript
ContextMenu = function() { this.constructor.apply(this, arguments); };
stjs.extend(ContextMenu, AbstractPopupContainer, [], function(constructor, prototype) {
    prototype.constructor = function(items, withDelete) {
        ... constructor ...
    };

    prototype.buildMenu = function(items) {
        ...
        var menuItems = buildMenuItems(items);
        ...
    };
    function buildMenuItems(models) {
        ... private logic here ...
    };
}, {...}, {});
```

**Comment by npiguet** [comment]
The problem with your proposal seems to be the binding of the "this" keyword. Each call to a private method must also have this bound properly, which is not the case here.

**Comment by onigoetz** [comment]
Yeah, it seems my solution is not fully baked.

I'll come back some day with something that has a chance to work.
