### ISSUE TITLE
Failing builds / bridging local dependencies

### ISSUE THREAD

**Issue by golanhall** [st-js/st-js#77]
I have a project with different modules, having their own seperate versioning (no master POM).
When I try to build modB which depends on modA (deployed jar with sources), I'm getting a build error asking for annotating the dependencies STJSBridge.

It doesn't make sense that a bridge has to be created for available java stjs sourcecode. Or am I missing something here?

Current options here are:
- creating a bridge-module/project modA with just interfaces. Feels a bit clunky when you have the java sources available.
- generating js for modA, followed by annotating modA sources with STJSBridge and install/deploy the module. The downside is that you'll have to repeat those 2 steps for every structural change you make.
- change maven build / add lifecycle differentiating between generating and deploying (excluding package-info.java files?) by using build profiles?

**Comment by npiguet** [comment]
Make sure that the jar artifacts resulting from your maven builds includes 
the small .stjs files right next to the .class files. St-js uses those 
files to store important meta-data needed for the coffee generation 
process, and it will complain of our can't find it.

**Comment by golanhall** [comment]
Argh!.. overlooked adding the .stjs files to the jar. Seems to be working now, thanks for the feedback.
