### ISSUE TITLE
The java for in loop hasn't the same semantic as the generated js code

### ISSUE THREAD

**Issue by Tapsi** [st-js/st-js#80]
At the moment stjs compiles the snippet

    for (MyClass x: Array<MyClass> xArr) { ... }

into the following code.

    for (var x in xArr) {
        if (!(xArr).hasOwnProperty(x)) continue;
        ...
    }

This iterates throught the property list instead of the value list (e.g. array indexes). Isn't it a better way to convert the java snippet into the following code. 
   
    for (var generatedIndex = 0; generatedIndex < xArr.length; generatedIndex++) {
        var x = xArr[generatedIndex];
        ...
    }

I know this ```generatedIndex``` would need a bit of work to be safe for use in a scope. But in my optionion this would be a lot better _(if I compare the java statement java with the generated js code)_ and it would be a lot easier to iterate through stjs arrays in java code.

**Comment by npiguet** [comment]
It wouldn't be better as that would yield the wrong data type for the key. 
If we generated the second version, from a Java for-in loop, then the 
counter would be a Number in js, but a String in Java. We would 
deliberately be breaking type safety, and defeating the point of using 
st-js in the first place.

The natural workaround is to use a traditional for loop (with increment) in 
Java, or to use Array.forEach.
