### ISSUE TITLE
mvn stjs:watch

### ISSUE THREAD

**Issue by onigoetz** [st-js/st-js#87]
Add a command to watch for changes and recompile on the fly.

A naive first implementation would recompile everything on a single class change.

A second version would create a tree of dependencies and recompile only the needed parts when things change.

This would be awesome for many development environments, as Eclipse is not the preferred environment for many people

**Comment by acraciun** [comment]
you can also use the watch command in unix - as the generator is incremental.

`watch mvn process-classes`
