### ISSUE TITLE
Add Callback5 and Function5 to shared

### ISSUE THREAD

**Issue by micw** [st-js/st-js#91]
This is required for Angular 1.4.x bridge. I could put it to the bridge jar but that's not the right place.

**Comment by micw** [comment]
I've added a PullRequest #92 for this

**Comment by npiguet** [comment]
We really think that this is unnecessary. A Callback5 becomes completely unreadable and we consider that be an anti-pattern.

Going all the way to 4 is already very nice. Java itself stops at 2...

If you need an callback type with more than 4 parameters, the best thing to do is to define your own interface in your bridge using a name that makes sense for your case, such as "EventHandler" or "PostProcessor" or something like that.
