### ISSUE TITLE
Discussion: tagging interfaces for functions/callbacks with 0...N arguments

### ISSUE THREAD

**Issue by micw** [st-js/st-js#93]
The problem:
In Javascript, callback functions are often defined with optional params like:
function(p1,p2,[p3],[p4])

On the java side this it means a function/callback 2..4 can be used here. to make the java side of the API better (stricter) typed, I had the idea to create tagging interfaces like Function2to4 which are extended by Function2, Function3, Function4.

I'll play a bit with that idea on a separate branch and show the results here.

**Comment by npiguet** [comment]
Actually, the correct way to declare that in Java is to use overriden method declarations:

```
public native void myFunction(Callback2<...>);
public native void myFunction(Callback3<...>)
public native void myFunction(Callback4<...>)
```

This is already used extensively in existing bridges.

Is there any reason this would not work for you?

**Comment by micw** [comment]
It won't work with types like angular's scope that are only holder objects for properties and callbacks.

Example: The "Directive" object (https://code.angularjs.org/1.4.3/docs/api/ng/service/$compile#directive-definition-object) contains a callback "link" with 1...5 arguments. So I define a property

public Callback5<...> link; 

No way to define Callback0...4 with the same name.

**Comment by micw** [comment]
Update: my idea was to have an interface like Callback0to3<P1,P2,P3> and let Callback1 extend Callback0to3. Unfortunately there's no way to create a construct for Callback1 where one can qualify P1 and use a wildcard for P2 and P3.

**Comment by npiguet** [comment]
For this particular case, it seems to me that the best way would be to define one interface called DirectiveLink that has a single method with 5 parameters. Anybody who wants to use this has to declare all 5 parameters whether they use them or not. It's not so bad to use when using the Java 8 lambda syntax.

Another possibility for this case could be to leverage the ST-JS "toProperty" template, which transforms JavaScript properties to Java methods (which you can then overload):
```java
@STJSBridge
public class Directive {
    @Template("toProperty")
    public native void link(Callback1<Scope> link);

    @Template("toProperty")
    public native void link(Callback2<Scope, Element> link);

    @Template("toProperty")
    public native Callback link();
}
```

You can then use it like this
```java
public void doSomething(){
    Directive d = new Directive();
    d.link(scope -> console.log(scope));
    console.log(d.link());
}
```

Which translated to the following Javascript
```
doSomething = function(){
    Directive d = new Directive();
    d.link = function(scope){console.log(scope);};
    console.log(d.link);
}
```

**Comment by npiguet** [comment]
I'll have to concede that @Template is badly documented, but it is pretty powerful. You will find a short paragraph about it at http://st-js.github.io/reference.html

**Comment by micw** [comment]
Thank you very much. This solved my problem in a very elegant way. It also solved another issue for me: properties than can be "a Map or a Boolean" - the bridge uses "object" for this at the moment.

Would you recommend to create special Callback-Objects for those?

    @Template("toProperty")
    public native void link(Callback3<? extends Scope,JQueryCore<JQueryCore<?>>,Attributes> link);
    @Template("toProperty")
    public native void link(Callback4<? extends Scope,JQueryCore<JQueryCore<?>>,Attributes,?> link);

There's another one with 5 params - so i'd need Callback5 here (see #91,#92) or I'd need to create DirectiveLinkCallback3, DirectiveLinkCallback4 and DirectiveLinkCallback5 (lot of code in the bridge).

**Comment by micw** [comment]
I have changed the code to work like you described. Unfortunately this breaks the nice "Object creation block" stuff:

new Directive() {{
                   templateUrl="template1.html";
                   link((DirectiveLinkCallback3<AbcScope>) (scope,element,attributes) -> new Abc(scope, element, attributes));
            }}

gives "Only assign expression are allowed in an object creation block"

Do you have any idea if we can solve this as well? Shall I create a new feature request issue?

**Comment by npiguet** [comment]
For all those Directive callbacks, maybe you could put the interfaces as inner classes of Directive, which makes a little less mess in your bridge

```java
public class Directive {

  ...

  public interface Link1 extends Callback1<...>{}
  public interface Link2 extends Callback2<...>{}
  public interface Link5 <..>{...}

  // You can then refer to the interfaces as Directive.Link5, for example
}
```

For the `Only assign expression are allowed in an object creation block`, I suggest you open a new issue, mentioning that it doesn't work as expected with `@Template("toProperty")`

**Comment by npiguet** [comment]
Now that you have created #94, do you think this issue can be closed?

**Comment by micw** [comment]
Sure :-)
