### ISSUE TITLE
St-js tests debugging: add a button which would allow to control tests running from browser UI

### ISSUE THREAD

**Issue by lumixen** [st-js/st-js#98]
Currently debug flow for tests is following:
1. Add $js("debugger") which will trigger breakpoint in browser debugger
2. Run test\s
3. Quickly press F12 (in chrome) to open debugger window before $js("debugger") line is executed

Sometimes it becomes incredibly hard to open debug console before tests execution, especially after recent tests runner speed improvements.

As a brief workaround there might be added a button to the browser UI which will trigger tests execution. Also, this button certainly should be configurable via appropriate property and disabled by default to leave tests runnable in automated environments.

**Comment by npiguet** [comment]
fixed by a bunch of recent commits. With the extra feature that if you have started the ST-JS test from your IDE using the IDE's "debug" feature, ST-JS understands what you are trying to do and starts the JS unit tests in JS debug mode.
